export default function Subjects() {
  let subjects = [
    { id: 1, value: 'Early Childhood Development (ECD)' },
    { id: 2, value: 'Foundation Phase (General)' },
    { id: 3, value: 'Literacy / Reading' },
    { id: 4, value: 'Numeracy / Mathematics (Foundation Phase)' },
    { id: 5, value: 'Life Skills' },
    { id: 6, value: 'Creative Arts' },
    { id: 7, value: 'Music' },
    { id: 8, value: 'Physical Education' },
    { id: 9, value: 'Afrikaans' },
    { id: 10, value: 'English (Home Language / First Additional Language)' },
    { id: 11, value: 'isiZulu' },
    { id: 12, value: 'isiXhosa' },
    { id: 13, value: 'Sesotho' },
    { id: 14, value: 'Setswana' },
    { id: 15, value: 'Grade R Educator' },
    { id: 16, value: 'Preschool Teacher' },
    { id: 17, value: 'Mathematics' },
    { id: 18, value: 'Natural Sciences & Technology' },
    { id: 19, value: 'Social Sciences' },
    { id: 20, value: 'Economic & Management Sciences (EMS)' },
    { id: 21, value: 'Religious Education' },
    { id: 22, value: 'Values Education' },
    { id: 23, value: 'Information & Communication Technology (ICT)' },
    { id: 24, value: 'Coding & Robotics' },
    { id: 25, value: 'Natural Sciences' },
    { id: 26, value: 'Technology' },
    { id: 27, value: 'Life Orientation' },
    { id: 28, value: 'Computer Applications Technology (CAT)' },
    { id: 29, value: 'English Home Language' },
    { id: 30, value: 'Afrikaans Home Language' },
    { id: 31, value: 'African Languages' },
    { id: 32, value: 'Mathematical Literacy' },
    { id: 33, value: 'Physical Sciences' },
    { id: 34, value: 'Life Sciences' },
    { id: 35, value: 'Geography' },
    { id: 36, value: 'History' },
    { id: 37, value: 'Business Studies' },
    { id: 38, value: 'Accounting' },
    { id: 39, value: 'Economics' },
    { id: 40, value: 'Consumer Studies' },
    { id: 41, value: 'Hospitality Studies' },
    { id: 42, value: 'Information Technology (IT)' },
    { id: 43, value: 'Visual Arts' },
    { id: 44, value: 'Design' },
    { id: 45, value: 'Dramatic Arts' },
    { id: 46, value: 'Music (Senior)' },
    { id: 47, value: 'Tourism' },
    { id: 48, value: 'Agricultural Sciences' },
    { id: 49, value: 'Engineering Graphics & Design (EGD)' },
    { id: 50, value: 'Technical Mathematics' },
    { id: 51, value: 'Technical Science' },
    { id: 52, value: 'Civil Technology' },
    { id: 53, value: 'Electrical Technology' },
    { id: 54, value: 'Mechanical Technology' },
    { id: 55, value: 'Education (General)' },
    { id: 56, value: 'Engineering Studies' },
    { id: 57, value: 'Business Management' },
    { id: 58, value: 'Administration (Academic)' },
    { id: 59, value: 'Information Technology / Computer Science' },
    { id: 60, value: 'Accounting & Finance' },
    { id: 61, value: 'Marketing / Entrepreneurship' },
    { id: 62, value: 'Human Resource Management' },
    { id: 63, value: 'Hospitality / Tourism Management' },
    { id: 64, value: 'Health Sciences / Nursing Education' },
    { id: 65, value: 'Agricultural Studies' },
    { id: 66, value: 'Law / Legal Studies' },
    { id: 67, value: 'Psychology / Social Work' },
    { id: 68, value: 'Art & Design / Architecture' },
    { id: 69, value: 'Communication / Media / Journalism' },
    { id: 70, value: 'Language Studies / Linguistics' },
    { id: 71, value: 'Research / Academic Support' },
    { id: 72, value: 'Classroom Teacher' },
    { id: 73, value: 'Substitute Teacher' },
    { id: 74, value: 'Head of Department (HOD)' },
    { id: 75, value: 'Deputy Principal' },
    { id: 76, value: 'Principal / School Head' },
    { id: 77, value: 'Teaching Assistant / Aide' },
    { id: 78, value: 'Aftercare Teacher / Supervisor' },
    { id: 79, value: 'Student Teacher / Intern' },
    { id: 80, value: 'Non-Teaching: Administrative / Support' },
    { id: 81, value: 'Non-Teaching: Specialist / Professional (e.g., Psychologist, Counsellor, Therapist)' },
    { id: 82, value: 'Non-Teaching: Operations / General Staff (e.g., Maintenance, Security, Transport, Catering)' },
    { id: 83, value: 'General Staff' },
    { id: 84, value: 'Volunteer' },
    { id: 85, value: 'Management / Leadership' },
    { id: 86, value: 'Other' },
  ];
  return subjects;
}
